// <auto-generated />
using System;
using ContextRepro;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContextRepro.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContextRepro.Entity.Belege.Beleg", b =>
                {
                    b.Property<long>("BelegId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BelegId"));

                    b.Property<long?>("BelegAdresse_AdressId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("BelegGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long?>("VersandAdresse_AdressId")
                        .HasColumnType("bigint");

                    b.Property<long?>("VorgangId")
                        .HasColumnType("bigint");

                    b.HasKey("BelegId")
                        .HasName("PK_dbo.Beleg");

                    b.HasIndex("BelegAdresse_AdressId")
                        .HasDatabaseName("IX_BelegAdresse_AdressId");

                    b.HasIndex("VersandAdresse_AdressId")
                        .HasDatabaseName("IX_VersandAdresse_AdressId");

                    b.HasIndex("VorgangId")
                        .HasDatabaseName("IX_VorgangId");

                    b.ToTable("Beleg", (string)null);
                });

            modelBuilder.Entity("ContextRepro.Entity.Belege.BelegAdresse", b =>
                {
                    b.Property<long>("AdressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AdressId"));

                    b.Property<Guid>("AdressGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("('00000000-0000-0000-0000-000000000000')");

                    b.Property<long>("KontaktId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdressId")
                        .HasName("PK_dbo.BelegAdresse");

                    b.HasIndex("KontaktId")
                        .HasDatabaseName("IX_KontaktId");

                    b.ToTable("BelegAdresse", (string)null);
                });

            modelBuilder.Entity("ContextRepro.Entity.Belege.Kontakt", b =>
                {
                    b.Property<long>("KontaktId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("KontaktId"));

                    b.Property<Guid>("KontaktGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("('00000000-0000-0000-0000-000000000000')");

                    b.Property<string>("KundenNummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KontaktId")
                        .HasName("PK_dbo.Kontakt");

                    b.ToTable("Kontakt");
                });

            modelBuilder.Entity("ContextRepro.Entity.Belege.Vorgang", b =>
                {
                    b.Property<long>("VorgangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("VorgangId"));

                    b.Property<long>("KontaktId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("VorgangGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("VorgangId")
                        .HasName("PK_dbo.Vorgang");

                    b.HasIndex("KontaktId")
                        .HasDatabaseName("IX_KontaktId");

                    b.ToTable("Vorgang", (string)null);
                });

            modelBuilder.Entity("ContextRepro.Entity.Belege.Beleg", b =>
                {
                    b.HasOne("ContextRepro.Entity.Belege.BelegAdresse", "BelegAdresse")
                        .WithOne()
                        .HasForeignKey("ContextRepro.Entity.Belege.Beleg", "BelegAdresse_AdressId")
                        .HasConstraintName("FK_Beleg_dbo.BelegAdresse_BelegAdresse_AdressId");

                    b.HasOne("ContextRepro.Entity.Belege.BelegAdresse", "VersandAdresse")
                        .WithOne()
                        .HasForeignKey("ContextRepro.Entity.Belege.Beleg", "VersandAdresse_AdressId")
                        .HasConstraintName("FK_Beleg_dbo.BelegAdresse_VersandAdresse_AdressId");

                    b.HasOne("ContextRepro.Entity.Belege.Vorgang", "Vorgang")
                        .WithMany("Belege")
                        .HasForeignKey("VorgangId")
                        .HasConstraintName("FK_Beleg_dbo.Vorgang_VorgangId");

                    b.Navigation("BelegAdresse");

                    b.Navigation("VersandAdresse");

                    b.Navigation("Vorgang");
                });

            modelBuilder.Entity("ContextRepro.Entity.Belege.BelegAdresse", b =>
                {
                    b.HasOne("ContextRepro.Entity.Belege.Kontakt", "Kontakt")
                        .WithMany()
                        .HasForeignKey("KontaktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.BelegAdresse_dbo.Kontakt_KontaktId");

                    b.Navigation("Kontakt");
                });

            modelBuilder.Entity("ContextRepro.Entity.Belege.Vorgang", b =>
                {
                    b.HasOne("ContextRepro.Entity.Belege.Kontakt", "Kontakt")
                        .WithMany()
                        .HasForeignKey("KontaktId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_dbo.Vorgang_dbo.Kontakt_KontaktId");

                    b.Navigation("Kontakt");
                });

            modelBuilder.Entity("ContextRepro.Entity.Belege.Vorgang", b =>
                {
                    b.Navigation("Belege");
                });
#pragma warning restore 612, 618
        }
    }
}
